/**
 * hooks.test.ts — T-298 A1 QA-LOW regression (same-pattern defect as T-284).
 *
 * `installPrePushHook`'s generated pre-push shell script hardcoded the
 * `.productune/git-rules.json` path literal in its body. In a prdt
 * (`.prdt`-only) project the installed hook would look for git-rules.json in
 * the wrong directory and silently fall back to the hard-coded default
 * (`protectedBranches: ["main"]`) instead of the project's actual rules.
 *
 * Fix: the generated script body must reference the project-kind-correct
 * rules path (`.prdt/git-rules.json` vs legacy `.productune/git-rules.json`),
 * using core's own `state/project-kind.ts` detection. Legacy projects must
 * get a byte-identical script to before.
 */

import path from 'path'
import fs from 'fs'
import os from 'os'
import { test, expect } from 'vitest'
import { installPrePushHook } from '../../src/git-workflow/hooks'

function makeProject(subdirs: string[]): string {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'core-hooks-'))
  for (const s of subdirs) fs.mkdirSync(path.join(root, s), { recursive: true })
  return root
}

function readHook(projectDir: string): string {
  return fs.readFileSync(path.join(projectDir, '.git', 'hooks', 'pre-push'), 'utf-8')
}

test('prdt project (.prdt only): generated pre-push script reads .prdt/git-rules.json', async () => {
  const d = makeProject(['.prdt', '.git'])

  await installPrePushHook(d)

  const script = readHook(d)
  expect(script).toContain('.prdt/git-rules.json')
  expect(script).not.toContain('.productune/git-rules.json')
})

test('legacy project (.productune only): generated pre-push script still reads .productune/git-rules.json (unchanged)', async () => {
  const d = makeProject(['.productune', '.git'])

  await installPrePushHook(d)

  const script = readHook(d)
  expect(script).toContain('.productune/git-rules.json')
  expect(script).not.toContain('.prdt/git-rules.json')
})

test('legacy project script body is byte-identical to the pre-existing hard-coded template', async () => {
  const d = makeProject(['.productune', '.git'])

  await installPrePushHook(d)

  const script = readHook(d)
  expect(script).toBe(`#!/bin/sh
# productune managed pre-push hook
# Edit .productune/git-rules.json to change the protected list.
# Auto-generated by T-P4-020. Do not edit manually.

PROTECTED_BRANCHES="$(cat .productune/git-rules.json 2>/dev/null \\
  | sed -n 's/.*"protectedBranches"[[:space:]]*:[[:space:]]*\\[\\([^]]*\\)\\].*/\\1/p' \\
  | tr -d '" ' | tr ',' '\\n')"

if [ -z "$PROTECTED_BRANCHES" ]; then
  PROTECTED_BRANCHES="main"
fi

while read local_ref local_sha remote_ref remote_sha; do
  branch="\${remote_ref#refs/heads/}"
  for protected in $PROTECTED_BRANCHES; do
    if [ "$branch" = "$protected" ]; then
      echo ""
      echo "  이 작업 줄기는 직접 보낼 수 없어요."
      echo "  배포 준비 단계를 거쳐 보내주세요."
      echo ""
      echo "  (대상 = $protected)"
      echo ""
      exit 1
    fi
  done
done

exit 0
`)
})
