#!/usr/bin/env bash
# migrate-graphiti-to-fs.sh — export Graphiti wiki episodes to ~/.productune/wiki/ markdowns.
# Run when switching from WIKI_BACKEND=graphiti to keeper or fs.
# Requires: Graphiti MCP running (productune.env sourced), claude CLI.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PO_ENV_FILE="$HOME/.productune/productune.env"
WIKI_BASE="$HOME/.productune/wiki"

say()  { printf "\033[1;34m[migrate]\033[0m %s\n" "$*"; }
warn() { printf "\033[1;33m[migrate]\033[0m %s\n" "$*" >&2; }
die()  { printf "\033[1;31m[migrate]\033[0m %s\n" "$*" >&2; exit 1; }

# Source env for Graphiti settings
[ -f "$PO_ENV_FILE" ] && set -a && source "$PO_ENV_FILE" && set +a

command -v claude >/dev/null || die "claude CLI not found"
command -v jq     >/dev/null || die "jq not found"

say "Graphiti → filesystem wiki migration"
say "Destination: $WIKI_BASE"
echo

regenerate_index() {
  local dir="$1"
  local persona="$2"
  {
    echo "# $persona wiki index"
    echo "<!-- auto-generated by migrate-graphiti-to-fs.sh -->"
    echo ""
    ls -r "$dir"/*.md 2>/dev/null | grep -v INDEX | while read -r f; do
      local name date superseded status body
      name=$(grep -m1 "^episode_name:" "$f" 2>/dev/null | sed 's/episode_name: //' || echo "unknown")
      date=$(grep -m1 "^created_at:" "$f" 2>/dev/null | sed 's/created_at: //' | cut -c1-10 || echo "unknown")
      superseded=$(grep -m1 "^superseded_by:" "$f" 2>/dev/null | sed 's/superseded_by: //' || echo "null")
      status="active"
      [[ "$superseded" != "null" && -n "$superseded" ]] && status="superseded"
      body=$(tail -n +6 "$f" 2>/dev/null | head -1 | cut -c1-80 || echo "")
      echo "- [$date] $name [$status]"
      [ -n "$body" ] && echo "  $body"
    done
  } > "$dir/INDEX.md"
}

for persona in designer developer qa; do
  GROUP="persona-$persona"
  WIKI_DIR="$WIKI_BASE/$GROUP"
  mkdir -p "$WIKI_DIR"

  say "Exporting $GROUP episodes from Graphiti..."

  # Invoke persona to dump its episodes via get_episodes
  TMP=$(mktemp)
  NO_COLOR=1 claude --agent "pdt-$persona" --model haiku \
    --print --output-format json \
    "Call mcp__graphiti__get_episodes with limit=10000. Return ONLY the raw JSON array from the tool result, nothing else. Format: [{\"name\":\"...\",\"episode_body\":\"...\",\"created_at\":\"...\"}]" \
    > "$TMP" 2>/dev/null || {
      warn "Failed to export $GROUP — skipping (Graphiti may not be running)"
      rm -f "$TMP"
      continue
    }

  # Extract episode JSON from the result field
  EPISODES=$(python3 - "$TMP" <<'PY'
import json, sys, re
raw = open(sys.argv[1]).read()
try:
    data = json.loads(raw)
    result = data.get("result", "")
    # Find JSON array in result
    match = re.search(r'\[.*\]', result, re.DOTALL)
    if match:
        arr = json.loads(match.group())
        print(json.dumps(arr))
    else:
        print("[]")
except Exception as e:
    print("[]")
PY
)

  COUNT=$(echo "$EPISODES" | jq 'length')
  say "  Found $COUNT episodes in $GROUP"

  echo "$EPISODES" | jq -c '.[]' 2>/dev/null | while IFS= read -r ep; do
    NAME=$(echo "$ep" | jq -r '.name // "unnamed"')
    BODY=$(echo "$ep" | jq -r '.episode_body // ""')
    CREATED=$(echo "$ep" | jq -r '.created_at // ""')

    # Derive timestamp and slug
    if [ -n "$CREATED" ]; then
      TS=$(echo "$CREATED" | sed 's/[:.]/-/g' | cut -c1-19)
    else
      TS=$(date -u +%Y-%m-%dT%H-%M-%SZ)
    fi
    SLUG=$(echo "$NAME" | tr '[:upper:]' '[:lower:]' | tr ' ' '-' | tr -cs 'a-z0-9-' '-' | sed 's/-*$//')
    FILE="$WIKI_DIR/${TS}--${SLUG}.md"

    cat > "$FILE" <<EOF
---
persona: pdt-$persona
episode_name: $NAME
created_at: ${CREATED:-$(date -u +%FT%TZ)}
superseded_by: null
related: []
migrated_from: graphiti
---
$BODY
EOF
    say "  → $FILE"
  done

  regenerate_index "$WIKI_DIR" "$GROUP"
  say "  INDEX regenerated: $WIKI_DIR/INDEX.md"
  rm -f "$TMP"
done

echo
say "Migration complete."
say "Next: update WIKI_BACKEND in $PO_ENV_FILE"
say "  sed -i.bak 's/^WIKI_BACKEND=.*/WIKI_BACKEND=keeper/' \"$PO_ENV_FILE\""
say "Then re-run install.sh to activate the keeper/fs agent variants."
