import fs from 'fs'
import path from 'path'
import { detectProjectKind, STATE_DIR_NAME } from '../state/project-kind'

const HOOK_MARKER = '# productune managed pre-push hook'

/**
 * Build the generated pre-push script body. `rulesDirName` is the
 * project-kind-correct state directory (`.prdt` or legacy `.productune`) so
 * the installed hook reads the same git-rules.json the rest of core writes
 * to (T-298 A1 QA-LOW fix — was hardcoded to `.productune`, silently
 * falling back to default protectedBranches in `.prdt` projects).
 */
function prePushScript(rulesDirName: string): string {
  return `#!/bin/sh
# productune managed pre-push hook
# Edit ${rulesDirName}/git-rules.json to change the protected list.
# Auto-generated by T-P4-020. Do not edit manually.

PROTECTED_BRANCHES="$(cat ${rulesDirName}/git-rules.json 2>/dev/null \\
  | sed -n 's/.*"protectedBranches"[[:space:]]*:[[:space:]]*\\[\\([^]]*\\)\\].*/\\1/p' \\
  | tr -d '" ' | tr ',' '\\n')"

if [ -z "$PROTECTED_BRANCHES" ]; then
  PROTECTED_BRANCHES="main"
fi

while read local_ref local_sha remote_ref remote_sha; do
  branch="\${remote_ref#refs/heads/}"
  for protected in $PROTECTED_BRANCHES; do
    if [ "$branch" = "$protected" ]; then
      echo ""
      echo "  이 작업 줄기는 직접 보낼 수 없어요."
      echo "  배포 준비 단계를 거쳐 보내주세요."
      echo ""
      echo "  (대상 = $protected)"
      echo ""
      exit 1
    fi
  done
done

exit 0
`
}

function hookPath(projectDir: string): string {
  return path.join(projectDir, '.git', 'hooks', 'pre-push')
}

export async function installPrePushHook(projectDir: string): Promise<void> {
  const hp = hookPath(projectDir)
  const hooksDir = path.dirname(hp)

  fs.mkdirSync(hooksDir, { recursive: true })

  if (fs.existsSync(hp)) {
    const existing = fs.readFileSync(hp, 'utf-8')
    if (existing.includes(HOOK_MARKER)) {
      // already productune hook — overwrite to update
    } else {
      // OQ-T020-1: backup existing hook
      const backup = `${hp}.bak.${Date.now()}`
      fs.copyFileSync(hp, backup)
    }
  }

  const rulesDirName = STATE_DIR_NAME[detectProjectKind(projectDir)]
  fs.writeFileSync(hp, prePushScript(rulesDirName), { mode: 0o755 })
}

export function isPrePushHookInstalled(projectDir: string): boolean {
  const hp = hookPath(projectDir)
  if (!fs.existsSync(hp)) return false
  try {
    const content = fs.readFileSync(hp, 'utf-8')
    return content.includes(HOOK_MARKER)
  } catch {
    return false
  }
}
