import fs from 'fs'
import path from 'path'
import { codeRoot } from '../state/project-kind'

const HOOK_MARKER = '# productune managed pre-push hook'

/**
 * Build the generated pre-push script body.
 *
 * git runs the pre-push hook with cwd = the CODE work-tree = codeRoot. In
 * LEGACY layout codeRoot == projectRoot, so `.prdt/git-rules.json` sits right
 * there. Once PHYSICALLY SPLIT (PRD §v1.3) codeRoot is `<projectRoot>/<code.dir>`
 * and the state dir lives one level UP — a hard-coded relative `.prdt/…` would
 * miss it and silently fall back to the default protected list (the exact
 * T-298 / T-284 defect class). So the script UP-WALKS from `$PWD` to find the
 * nearest ancestor carrying `.prdt/git-rules.json` (or legacy
 * `.productune/git-rules.json`, `.prdt` preferred). This is layout-agnostic:
 * legacy finds it at depth 0, split at depth 1.
 */
function prePushScript(): string {
  return `#!/bin/sh
# productune managed pre-push hook
# Edit <state-dir>/git-rules.json to change the protected list.
# Auto-generated by T-P4-020. Do not edit manually.

# Up-walk from the code work-tree to the prdt state dir (parent under v1.3 split).
RULES=""
dir="$PWD"
while [ -n "$dir" ] && [ "$dir" != "/" ]; do
  if [ -f "$dir/.prdt/git-rules.json" ]; then RULES="$dir/.prdt/git-rules.json"; break; fi
  if [ -f "$dir/.productune/git-rules.json" ]; then RULES="$dir/.productune/git-rules.json"; break; fi
  dir="$(dirname "$dir")"
done

PROTECTED_BRANCHES="$(cat "$RULES" 2>/dev/null \\
  | sed -n 's/.*"protectedBranches"[[:space:]]*:[[:space:]]*\\[\\([^]]*\\)\\].*/\\1/p' \\
  | tr -d '" ' | tr ',' '\\n')"

if [ -z "$PROTECTED_BRANCHES" ]; then
  PROTECTED_BRANCHES="main"
fi

while read local_ref local_sha remote_ref remote_sha; do
  branch="\${remote_ref#refs/heads/}"
  for protected in $PROTECTED_BRANCHES; do
    if [ "$branch" = "$protected" ]; then
      echo ""
      echo "  이 작업 줄기는 직접 보낼 수 없어요."
      echo "  배포 준비 단계를 거쳐 보내주세요."
      echo ""
      echo "  (대상 = $protected)"
      echo ""
      exit 1
    fi
  done
done

exit 0
`
}

/** The pre-push hook path — inside the CODE repo (codeRoot's `.git/hooks`). */
function hookPath(projectDir: string): string {
  return path.join(codeRoot(projectDir), '.git', 'hooks', 'pre-push')
}

export async function installPrePushHook(projectDir: string): Promise<void> {
  const hp = hookPath(projectDir)
  const hooksDir = path.dirname(hp)

  fs.mkdirSync(hooksDir, { recursive: true })

  if (fs.existsSync(hp)) {
    const existing = fs.readFileSync(hp, 'utf-8')
    if (existing.includes(HOOK_MARKER)) {
      // already productune hook — overwrite to update
    } else {
      // OQ-T020-1: backup existing hook
      const backup = `${hp}.bak.${Date.now()}`
      fs.copyFileSync(hp, backup)
    }
  }

  fs.writeFileSync(hp, prePushScript(), { mode: 0o755 })
}

export function isPrePushHookInstalled(projectDir: string): boolean {
  const hp = hookPath(projectDir)
  if (!fs.existsSync(hp)) return false
  try {
    const content = fs.readFileSync(hp, 'utf-8')
    return content.includes(HOOK_MARKER)
  } catch {
    return false
  }
}
