#!/usr/bin/env bash
# wiki-init.sh — initialize ~/.productune/wiki/ directory structure for markdown wiki backend.
# Called by install.sh when WIKI_BACKEND=keeper or WIKI_BACKEND=fs.
# Idempotent — safe to run multiple times.

set -euo pipefail

say()  { printf "\033[1;34m[wiki-init]\033[0m %s\n" "$*"; }
warn() { printf "\033[1;33m[wiki-init]\033[0m %s\n" "$*" >&2; }

WIKI_BASE="$HOME/.productune/wiki"

for persona in persona-designer persona-developer persona-qa; do
  DIR="$WIKI_BASE/$persona"
  mkdir -p "$DIR"

  INDEX="$DIR/INDEX.md"
  if [ ! -f "$INDEX" ]; then
    cat > "$INDEX" <<EOF
# $persona wiki index
<!-- auto-generated by wiki-keeper, do not edit manually -->

EOF
    say "created: $INDEX"
  else
    say "exists:  $INDEX (skipped)"
  fi
done

say "wiki filesystem initialized at $WIKI_BASE"
say "  $(ls "$WIKI_BASE" | tr '\n' '  ')"
